export const CARDIOLOGY_AND_GENERAL_MEDICATIONS = [
  'Acarbose',
  'Accenten',
  'Acetylsalicylic acid',
  'Adalat',
  'Adco-Zolpidem',
  'Adenosine',
  'Adrenaline',
  'Aldactone',
  'Alfuwin',
  'Alirocumab',
  'Aliskiren',
  'Allopurinol',
  'Alteplase',
  'Altosec',
  'Amiodarone',
  'Amlodipine',
  'Amlodipine/atorvastatin',
  'Amycor',
  'Apixaban',
  'Arycor',
  'Aspavor',
  'Aspirin',
  'Atacand',
  'Atenolol',
  'Atorvastatin',
  'Atropine',
  'Azilsartan',
  'Azzalure',
  'Bayers-Aspirin',
  'Benazepril',
  'Betaxolol',
  'Bilocor',
  'Bisoprolol',
  'Brexan',
  'Brilinta',
  'Bumetanide',
  'Candesartan',
  'Captopril',
  'Cardicor',
  'Carvedilol',
  'Carzin XL',
  'Chlorothiazide',
  'Cilift',
  'Ciplaza',
  'Clexane',
  'Clopidogrel',
  'Clopiwin',
  'Co-ecodyne',
  'Concor',
  'Copalia',
  'Coralan',
  'Cordarone',
  'Cosa Comp',
  'Coversyl',
  'Cozaar',
  'Crestor',
  'Cynt',
  'Dabigatran',
  'Dabiklot',
  'Daglif',
  'Dapagliflozin',
  'Dasit',
  'Deforzig',
  'Desperan Colio K',
  'Diaglucide MR',
  'Digoxin',
  'Dilatrend',
  'Diltiazem',
  'Diovan',
  'Disprin',
  'Disprin CV',
  'Dobutamine',
  'Dominal',
  'Donepezil',
  'Dopamine',
  'Dormonoct',
  'Dronedarone',
  'Duforzig',
  'Dupont',
  'Ebastine',
  'Ecotrin',
  'Edoxaban',
  'Effient',
  'Elantan',
  'Eliquis',
  'Eltroxin',
  'Emcor',
  'Enalapril',
  'Enoxaparin',
  'Entresto',
  'Epinephrine',
  'Eplerenone',
  'Epoprostenol',
  'Equitrin',
  'Esomeprazole',
  'Euthyrox',
  'Evolocumab',
  'Exinef',
  'Ezetimibe',
  'Ezetrol',
  'Ferrosamide',
  'Flecainide',
  'Folic acid',
  'Furosemide',
  'Fuso',
  'Galdus',
  'Gardecorn',
  'Glucophage XR',
  'Glyceryl trinitrate',
  'GTN',
  'Heparin',
  'Hexal',
  'Hexarone',
  'Hydralazine',
  'Hydrochlorothiazide',
  'Ibutilide',
  'Imcord',
  'Indapamide',
  'Indapamide SR',
  'Inspra',
  'Ismo',
  'Isoptin',
  'Isosorbide dinitrate',
  'Isosorbide mononitrate',
  'Ivabradine',
  'Ivedal',
  'Jalra',
  'Labetalol',
  'Lanoxin',
  'Lasix',
  'Lenditro',
  'Levothyroxine',
  'Lexamil',
  'Lipitor',
  'Lisinopril',
  'Lixiana',
  'Lomanor',
  'Loprazolam',
  'Losartan',
  'Losartan + HCTZ',
  'Melor',
  'Metoprolol',
  'Micardis',
  'Migrobin',
  'Milrinone',
  'Minoxidil',
  'Mixaran',
  'Mycelin',
  'Mysoline',
  'Nadolol',
  'Natrilix',
  'Nebivolol',
  'Neurobion',
  'Nicardipine',
  'Nifedipine',
  'Nirobian',
  'Nitroglycerin',
  'Noradrenaline',
  'Norepinephrine',
  'Olmesartan',
  'Paracetamol',
  'Pearinda',
  'Peploc',
  'Pericose',
  'Perindopril',
  'Phenergan',
  'Plenish K',
  'Potassium supplement',
  'Praluent',
  'Prasugrel',
  'Prava',
  'Pravastatin',
  'Pravulan',
  'Prexum',
  'Prexum Plus',
  'Procainamide',
  'Propafenone',
  'Propranolol',
  'Pulmicort',
  'Purata',
  'Puricos',
  'Ramipril',
  'Reaptan',
  'Renitec',
  'Repatha',
  'Revite SR',
  'Rezalto',
  'Ridaq',
  'Rivaroxaban',
  'Rosuvastatin',
  'Rythmol',
  'Sacubitril/valsartan',
  'Sameuls',
  'Sandoz Omeprazole',
  'Serdip',
  'Sertraline',
  'Sideral Forte',
  'Simvacor',
  'Simvastatin',
  'Slow K',
  'Slow-Mag',
  'Sotahexal',
  'Sotalol',
  'Spiractin',
  'Spironolactone',
  'Stapran',
  'Streptokinase',
  'Stugeron',
  'Symbicort',
  'Symbicort Turbuhaler',
  'Tambocor',
  'Telmisartan',
  'Tenecteplase',
  'Tenormin',
  'Thiamide',
  'Thiamine',
  'Ticagrelor',
  'Tilzem',
  'Torsemide',
  'Tramazac',
  'Trandolapril',
  'Trazodone',
  'Tritace',
  'Trustan',
  'Tymeco',
  'Urbanol',
  'Uromax',
  'Vagifem',
  'Valsartan',
  'Verahexal',
  'Verapamil',
  'Verohexyl',
  'Vusor',
  'Vymada',
  'Warfarin',
  'Xarelto',
  'Xefo',
  'Zartan',
  'Zestril',
  'Zocor',
  'Zolpidem',
  'Zuvamor',
  'Zyquis',
  'Zyrtec',
] as const;

export function buildMedicationGlossaryPromptBlock(): string {
  return `
MEDICATION SPELLING GLOSSARY:
The cardiologist commonly dictates the medication names below. Dictation/transcription may contain phonetic or misspelled versions.
- When a dictated medication clearly matches one of these names, use the exact spelling/capitalization from this glossary.
- Preserve dictated dose, route, frequency, start/stop/change instructions, and combination products.
- Do not add a medication that is not supported by the dictation.
- If uncertain between two medications, keep the dictated wording rather than guessing.

${CARDIOLOGY_AND_GENERAL_MEDICATIONS.join(', ')}
`.trim();
}
